# Config. file to train [1].
#
# [1] Bednarik Jan et al. Shape Reconstruction by Learning Differentiable
#     Surface Representations. CoRR 2019.
#
# Author: Jan Bednarik, jan.bednarik@epfl.ch
#

### Model
N: 2500
M: 5000   # train_uv_sample_size
code: 1024

# Encoder
enc_freeze: False
enc_weights: # Path, only needed if `enc_freeze`=True.
normalize_cw: False

# Decoder
num_patches: 25

# for FN decoder
dec_activ_fns: 'softplus'
dec_use_tanh: False
dec_batch_norm: False

# Losses
loss_scaled_isometry: True
alpha_scaled_isometry: 0.001
alphas_sciso:
  E: 1.
  G: 1.
  skew: 1.
  stretch: 0.
  total_area: 100
  total_area_mult: 1.

# Training
epochs: 1000
lr: 0.001

# lr scheduler
reduce_lr_on_plateau: True
lr_factor: 0.3
lr_patience: 30
lr_min: 0.000001
lr_threshold: 0.0001

# Savers
train_state_save_period: 1
